"""
app/models/state.py
────────────────────
Core placement state model shared across the application.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Optional
from enum import Enum

from pydantic import BaseModel, Field


class SessionPhase(str, Enum):
    """Which phase of the LangGraph pipeline the session is in."""
    INIT       = "init"
    PHASE_1    = "phase1"
    PHASE_2    = "phase2"
    COMPLETE   = "complete"


class PlacementState(BaseModel):
    """
    Represents the full mutable state that flows through both LangGraph phases.

    This model is intentionally flat so LangGraph can serialise / deserialise it
    without additional custom reducers.
    """

    # ── Identity ──────────────────────────────────────────────
    session_id: str = Field(..., description="Unique session identifier (UUID).")

    # ── User context ──────────────────────────────────────────
    user_message: str = Field(default="", description="Raw input from the user.")
    target_companies: list[str] = Field(default_factory=list)
    target_roles: list[str] = Field(default_factory=list)
    preparation_duration_days: int = Field(default=30)
    current_day: int = Field(default=1)

    # ── Phase 1 outputs ───────────────────────────────────────
    interpreted_intent: Optional[dict[str, Any]] = Field(
        default=None,
        description="Structured intent extracted by the MessageInterpreter agent.",
    )
    company_intel: Optional[dict[str, Any]] = Field(
        default=None,
        description="Company research produced by the CompanyIntel agent.",
    )
    vault_context: Optional[list[dict[str, Any]]] = Field(
        default=None,
        description="Relevant documents retrieved from the KnowledgeVault.",
    )

    # ── Phase 2 outputs ───────────────────────────────────────
    recall_questions: Optional[list[dict[str, Any]]] = Field(
        default=None,
        description="Recall / practice questions generated by the RecallAgent.",
    )
    curriculum: Optional[dict[str, Any]] = Field(
        default=None,
        description="Day-by-day study plan produced by CurriculumArchitect.",
    )

    # ── Metadata ──────────────────────────────────────────────
    phase: SessionPhase = Field(default=SessionPhase.INIT)
    errors: list[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    model_config = {"use_enum_values": True}
