import React from 'react';
import { 
  Building2, 
  FileText, 
  Sparkles, 
  Target, 
  AlertTriangle, 
  Layers, 
  ChevronRight,
  Globe,
  DollarSign,
  MapPin,
  CheckCircle2,
  Award
} from 'lucide-react';

export default function StrategyDashboard({ phase1Data, onGeneratePhase2, isLoadingPhase2 }) {
  if (!phase1Data) return null;

  const intent = phase1Data.interpreted_intent || {};
  const companyIntel = phase1Data.company_intel || {};
  const vaultContext = phase1Data.vault_context || [];

  return (
    <div className="animate-fade-in" style={{ maxWidth: '1040px', margin: '20px auto', padding: '0 20px' }}>
      
      {/* Header Banner */}
      <div className="glass-panel" style={{ padding: '24px', marginBottom: '28px', borderLeft: '4px solid var(--primary)' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '16px' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '6px' }}>
              <span className="badge badge-purple"><Sparkles size={14} /> Phase 1 Campus Notice Analysis Complete</span>
              <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Session: {phase1Data.session_id}</span>
            </div>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 700, margin: 0 }}>
              Campus Recruitment & Company Intelligence Summary
            </h2>
          </div>

          <button
            onClick={onGeneratePhase2}
            className="btn-primary"
            disabled={isLoadingPhase2}
            style={{ padding: '12px 24px', fontSize: '0.95rem' }}
          >
            {isLoadingPhase2 ? (
              <>⏳ Generating Study Plan...</>
            ) : (
              <>
                <Layers size={18} />
                Build Day-by-Day Study Plan →
              </>
            )}
          </button>
        </div>
      </div>

      {/* Grid: Extracted Intent & Skill Analysis */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '24px', marginBottom: '28px' }}>
        
        {/* Profile & Target Summary */}
        <div className="glass-card" style={{ padding: '24px' }}>
          <h3 style={{ fontSize: '1.1rem', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '16px' }}>
            <Target size={18} color="var(--primary)" /> Campus Placement Goal Summary
          </h3>
          <p style={{ fontSize: '0.9rem', color: 'var(--text-muted)', marginBottom: '16px', lineHeight: '1.5' }}>
            {intent.goal_summary || 'Campus recruitment preparation strategy generated by AI.'}
          </p>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}>
              <span style={{ color: 'var(--text-muted)' }}>Target Companies:</span>
              <span style={{ fontWeight: 600, color: '#c4b5fd' }}>
                {Array.isArray(intent.target_companies) && intent.target_companies.length > 0
                  ? intent.target_companies.join(', ')
                  : 'None Specified'}
              </span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}>
              <span style={{ color: 'var(--text-muted)' }}>Target Roles:</span>
              <span style={{ fontWeight: 600, color: '#67e8f9' }}>
                {Array.isArray(intent.target_roles) && intent.target_roles.length > 0
                  ? intent.target_roles.join(', ')
                  : 'None Specified'}
              </span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}>
              <span style={{ color: 'var(--text-muted)' }}>Timeline:</span>
              <span style={{ fontWeight: 600 }}>{intent.preparation_duration_days || 30} Days</span>
            </div>
          </div>
        </div>

        {/* Skill Gaps & Strengths */}
        <div className="glass-card" style={{ padding: '24px' }}>
          <h3 style={{ fontSize: '1.1rem', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '16px' }}>
            <AlertTriangle size={18} color="var(--accent-amber)" /> Identified Technical Focus Areas
          </h3>
          
          <div style={{ marginBottom: '16px' }}>
            <span style={{ fontSize: '0.75rem', fontWeight: 600, color: 'var(--text-muted)', display: 'block', marginBottom: '8px' }}>
              ⚡ REQUIRED TECHNICAL SKILLS:
            </span>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
              {Array.isArray(intent.skill_gaps) && intent.skill_gaps.length > 0 ? (
                intent.skill_gaps.map((gap, i) => <span key={i} className="badge badge-amber">{gap}</span>)
              ) : (
                <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>No specific skills identified</span>
              )}
            </div>
          </div>

          <div>
            <span style={{ fontSize: '0.75rem', fontWeight: 600, color: 'var(--text-muted)', display: 'block', marginBottom: '8px' }}>
              ✅ FOUNDATIONAL PREPARATION:
            </span>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
              {Array.isArray(intent.current_skills) && intent.current_skills.length > 0 ? (
                intent.current_skills.map((skill, i) => <span key={i} className="badge badge-emerald">{skill}</span>)
              ) : (
                <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>No current skills listed</span>
              )}
            </div>
          </div>
        </div>

      </div>

      {/* Target Companies Intelligence Cards */}
      <h3 style={{ fontSize: '1.3rem', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '16px' }}>
        <Building2 size={22} color="var(--primary)" /> Campus Recruitment Company Profiles
      </h3>

      {Object.keys(companyIntel).length === 0 ? (
        <div className="glass-panel" style={{ padding: '24px', textAlign: 'center', color: 'var(--text-muted)', marginBottom: '32px' }}>
          No company intelligence records returned for this run.
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px', marginBottom: '32px' }}>
          {Object.entries(companyIntel).map(([name, profile]) => (
            <div key={name} className="glass-panel" style={{ padding: '24px' }}>
              
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '12px', marginBottom: '16px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <div style={{
                    width: '40px', height: '40px', borderRadius: '12px',
                    background: 'linear-gradient(135deg, rgba(139, 92, 246, 0.3) 0%, rgba(6, 182, 212, 0.3) 100%)', display: 'flex',
                    alignItems: 'center', justifyContent: 'center', fontWeight: 800, color: '#c4b5fd', fontSize: '1.2rem'
                  }}>
                    {name.charAt(0)}
                  </div>
                  <div>
                    <h4 style={{ fontSize: '1.3rem', fontWeight: 700, margin: 0 }}>{profile.company_name || name}</h4>
                    {profile.website && (
                      <a href={profile.website} target="_blank" rel="noreferrer" style={{ fontSize: '0.8rem', color: '#67e8f9', textDecoration: 'none', display: 'inline-flex', alignItems: 'center', gap: '4px', marginTop: '2px' }}>
                        <Globe size={12} /> {profile.website}
                      </a>
                    )}
                  </div>
                </div>

                <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
                  {profile.ctc && <span className="badge badge-amber"><DollarSign size={12} /> CTC: {profile.ctc}</span>}
                  {profile.location && <span className="badge badge-cyan"><MapPin size={12} /> {profile.location}</span>}
                  {profile.batch && <span className="badge badge-purple">{profile.batch}</span>}
                </div>
              </div>

              {/* Eligibility Info */}
              {profile.eligibility && (
                <div style={{ background: 'rgba(0,0,0,0.2)', padding: '10px 16px', borderRadius: 'var(--radius-md)', marginBottom: '16px', fontSize: '0.85rem', color: 'var(--text-main)', display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <Award size={16} color="var(--accent-amber)" />
                  <strong>Academic Eligibility: </strong> {profile.eligibility}
                </div>
              )}

              {/* Selection Process Rounds */}
              {Array.isArray(profile.interview_rounds) && profile.interview_rounds.length > 0 && (
                <div style={{ marginBottom: '16px' }}>
                  <span style={{ fontSize: '0.8rem', fontWeight: 600, color: 'var(--text-muted)', display: 'block', marginBottom: '8px' }}>
                    🎯 SELECTION PROCESS ({profile.interview_rounds.length} ROUNDS):
                  </span>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                    {profile.interview_rounds.map((round, idx) => (
                      <div key={idx} style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.88rem', color: 'var(--text-main)' }}>
                        <ChevronRight size={14} color="var(--primary)" />
                        <span style={{ fontWeight: 600, color: '#c4b5fd' }}>Round {idx + 1}:</span> {round}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Frequently Asked Topics & Tips */}
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: '16px', background: 'rgba(0,0,0,0.2)', padding: '16px', borderRadius: 'var(--radius-md)' }}>
                {Array.isArray(profile.common_topics) && profile.common_topics.length > 0 && (
                  <div>
                    <span style={{ fontSize: '0.75rem', fontWeight: 600, color: 'var(--text-muted)', display: 'block', marginBottom: '6px' }}>
                      🔥 REQUIRED TECHNICAL SKILLS:
                    </span>
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
                      {profile.common_topics.map((topic, tidx) => (
                        <span key={tidx} className="badge badge-purple">{topic}</span>
                      ))}
                    </div>
                  </div>
                )}

                {profile.candidate_tips && (
                  <div>
                    <span style={{ fontSize: '0.75rem', fontWeight: 600, color: 'var(--text-muted)', display: 'block', marginBottom: '6px' }}>
                      💡 RECRUITMENT DRIVE PREPARATION TIP:
                    </span>
                    <p style={{ fontSize: '0.85rem', color: 'var(--text-main)', fontStyle: 'italic', margin: 0 }}>
                      "{profile.candidate_tips}"
                    </p>
                  </div>
                )}
              </div>

            </div>
          ))}
        </div>
      )}

      {/* Matched Knowledge Vault Resources */}
      <h3 style={{ fontSize: '1.2rem', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '16px' }}>
        <FileText size={20} color="var(--secondary)" /> Relevant Vault Materials Matched
      </h3>

      {vaultContext.length === 0 ? (
        <div className="glass-panel" style={{ padding: '24px', textAlign: 'center', color: 'var(--text-muted)', marginBottom: '32px' }}>
          No documents matched in vault context.
        </div>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '16px', marginBottom: '32px' }}>
          {vaultContext.map((item, idx) => (
            <div key={idx} className="glass-card" style={{ padding: '16px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                <span className="badge badge-cyan" style={{ fontSize: '0.7rem' }}>
                  {item.score ? `${Math.round(item.score * 100)}% Match` : 'Matched'}
                </span>
                <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>{item.file || item.metadata?.filename || 'Vault Document'}</span>
              </div>
              <p style={{ fontSize: '0.85rem', color: 'var(--text-main)', margin: 0, lineHeight: '1.4' }}>
                {item.content || item.document}
              </p>
            </div>
          ))}
        </div>
      )}

    </div>
  );
}
